apiVersion: v1
kind: Pod 
metadata:
  name: storage-pod
spec:
  containers:
  - image: nginx 
    name: my-frontend
    command:
      - sleep
      - "36000"
    volumeMounts:
      - mountPath: "/data"
        name: my-volume
  
  volumes: 
  - name: my-volume
    persistentVolumeClaim:
      claimName: pvc