apiVersion: v1
kind: Pod 
metadata:
  name: promethium-pvc 
spec:
  containers:
  - image: nginx 
    name: my-frontend
    volumeMounts:
      - mountPath: "/data"
        name: my-volume
  
  volumes: 
  - name: my-volume
    persistentVolumeClaim:
      claimName: pvc