apiVersion: v1
kind: Pod 
metadata:
  name: configmap-pod
spec:
  containers:
  - image: nginx 
    name: test-container
    volumeMounts:
      - mountPath: /etc/config
        name: config-volume
  
  volumes: 
  - name: config-volume
    configMap:
      name: dev-properties 
  
  restartPolicy: Never